name: Internal

on:
  push:
  workflow_dispatch: # To allow manual starting

permissions:
  actions: write
  contents: read
  packages: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets:
      TESTSECRET_SECRETSURL: ${{ secrets.TESTSECRET_SECRETSURL }}
      DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
      WHBUILD_BUILDBOTPASSWORD: ${{ secrets.WHBUILD_BUILDBOTPASSWORD }}
